rtslib/__init__.py, rtslib/fabric.py, rtslib/node.py, rtslib/root.py, rtslib/target.py, rtslib/tcm.py, rtslib/utils.py, setup.py
* Replace dict.iteritems() with six.iteritems(dict)
* Replace dict.itervalues() with six.itervalues(dict)
* Fix syntax of relative imports
* Get range from six.moves to get xrange() on Python 2 and range() on
Python 3
* Replace it.next() with next(it)
* Sort also imports
=> Port to Python 3

setup.py
This fixes this error:
```
File "setup.py", line 31
"classifiers": [
^
SyntaxError: invalid syntax
```
=> fix a syntax error in setup.py

rtslib/tcm.py
The purpose of this patch is to restore the pre v2.1.fb44 behaviour
when a storage object in not found in lookup mode. Prior to v2.1.fb44,
the RTSLibNotInCFS exception was raised. Since v2.1.fb44, a more
generic RTSLibError is raised instead.
This patch fixes issue #57.
=> Raise RTSLibNotInCFS when a storage object is not found in lookup mode

rtslib/target.py
This patch fixes an import error I introduced in the following commit:
7f6035f Fix the "unused import" warnings reported by Pylint
=> Fix missing import of RTSLibBrokenLink

rtslib/utils.py
Better, because it is sure to find the scsi parent.
You never know what intermediate parent might get interposed.
Better, becaus it does not rely on subsystem property
(which sometimes raises an AttributeError (fixed in pyudev 0.19)).
Signed-off-by: mulhern <amulhern@redhat.com>
=> Use find_parent instead of parent.

rtslib/tcm.py
The present parameter list is "name, config, size, wwn", update the
docstring to match this.
Signed-off-by: Fam Zheng <famz@redhat.com>
=> UserBackedStorageObject: Fix docstring for __init__

Makefile
To fix #61 added a mv from build/example-debian, to build/debian. Build is now working again on debian.
As it is in build folder, I guess it respects changes made to fix #59.
I'm not used with Makefiles, I don't know if it is the best way to do this !
=> Changed example-debian folder for compatibility with dpkg-buildpackage

setup.py
In v2.1.fb60 an unconditional dependency to pyudev was added,
which needs to be specified in the egg info, otherwise pip install might fail with e.g.
File "local/lib/python2.7/site-packages/rtslib/utils.py", line 30, in <module>
import pyudev
ImportError: No module named pyudev
=> Depend on pyudev during runtime

rtslib/fabric.py
Adds support for the IBM PowerVM virtual SCSI fabric.  This uses the
ibmvscsis kernel module that merged in 4.8 and later kernels.
=> Add IBM PowerVM vscsi fabric

rtslib/target.py
Pass through backends do not support alua_tg_pt_gp and writing to
the file will hang the system. Trying to read from them will
cause a rtslib crash because they are empty. This patch fixes
both issues by detecting the empty file and failing writes.
=> Do not set alua_tg_pt_gp if not supported

rtslib/__init__.py, rtslib/alua.py, rtslib/root.py, rtslib/target.py, rtslib/tcm.py, rtslib/utils.py
The following patches fix the targetctl crash due to the ALUA setup failing and raising an exception.
The patches also make so you cannot even create ALUA groups on backends that do not fully support ALUA.
=> Fix crash during restore due to ALUA exception

rtslib/__init__.py, rtslib/alua.py, rtslib/root.py, rtslib/target.py, rtslib/tcm.py, rtslib/utils.py
For efficiency, rtslib may have caches (today for the data
in configfs).  A client may need to clear out these caches
such as via the refresh option in targetcli.
* Add new invalidate_caches method to RTSRoot.  While this only
has a single cache today, it gives the ability to extend to
any future caches.
* While bs_cache really should be private, it probably
shouldn't be changed given that this is a library and may be
used elsewhere.
Signed-off-by: Amartey Pearson <apearson@us.ibm.com>
=> Add ability to invalidate caches

rtslib/alua.py
There is a bug in the kernel where if you map a backend device through
multiple targets/tpgts it only returns the first one. The rtslib
ALUA members function then returns a string containing whatever the kernel
prints out which is just the first lun the backend is mapped to. The
others are dropped. When the kernel is fixed this will print out a lun
mapping per line with the format:
driver/target/tpgt/lun\n
for each mapping.
This patch prepares us for the kernel getting fixed and returns
the lun mappings in a format that is easier for the rtslib user.
It will return a list of dictionarys with the format:
[{'tpgt': 'tpgt_1', 'driver': 'iSCSI', 'target':
'iqn.1999-09.com.tcmu:alua', 'lun': 'lun_3'}, {'tpgt': 'tpgt_2',
'driver': 'iSCSI', 'target': 'iqn.1999-09.com.tcmu:alua2', 'lun': …
=> ALUA: return list of members

rtslib/node.py
This patch allows users to pass in a string into the
attributes. Prior it would throw:
Traceback (most recent call last):
File "/usr/bin/targetcli", line 121, in <module>
main()
File "/usr/bin/targetcli", line 117, in main
root_node.ui_command_saveconfig()
File "/usr/lib/python3/dist-packages/targetcli/ui_root.py", line 98, in ui_command_saveconfig
self.rtsroot.save_to_file(savefile)
File "/usr/lib/python3/dist-packages/rtslib_fb/root.py", line 270, in save_to_file
f.write(json.dumps(self.dump(), sort_keys=True, indent=2))
File "/usr/lib/python3/dist-packages/rtslib_fb/root.py", line 160, in dump
d['storage_objects'] = [so.dump() for so in self.storage_objects]
File "/usr/lib/python3/dist-packages/rtslib_fb/root.py", line 160, in <listcomp>
d['storage_objects'] = [so.dump() for so in …
=> Support Reconfiguration of device path

rtslib/root.py, rtslib/tcm.py
This switches the kernel target driver directory from
the default of /var/target to /etc/target, if the
"dbroot" sysfs attribute is present. If not, the default
of /var/target is maintained. This has to be done
by rtslib/root.py since this module loads the
target_core_mod module, where the dbroot value
must be updated before any target_core_* drivers
register with target_core_mod.
=> Switch target driver DB root dir to /etc/target

rtslib/utils.py
In python 3.6, escape sequences that are not
recognized in string literals issue DeprecationWarnings.
Convert these to raw strings.
=> Fix python 3.6 escape char warnings in strings

rtslib/alua.py, rtslib/tcm.py
4.14 (it is currently the 4.13 feature window and I think we will
miss it) will add this patch
https://git.kernel.org/pub/scm/linux/kernel/git/nab/target-pending.git/commit/?h=for-next&id=c17d5d5f51f72f24e0e17a4450ae5010bf6962d9
commit c17d5d5f51f72f24e0e17a4450ae5010bf6962d9
Author: Mike Christie <mchristi@redhat.com>
Date:   Mon Jul 10 14:53:31 2017 -0500
target: export lio pgr/alua support as device attr
which has the lio device report if it supports lio based ALUA.
This patch has rtslib check the configfs alua_support file for pscsi and tcmu to check if alua is supported in the kernel. Note that we only check for those two, because older kernels always supported ALUA for backends like iblock and file and so they should return true even if the alua_support file does not exist in …
=> alua: enable alua for pscsi/tcmu if kernel reports support

rtslib/root.py
The "dbroot" configfs parameter allows to set the directory where
persistent information are stored by the kernel, such as persistent
reservations or ALUA.
Targetcli tries to change the value of the "dbroot" parameter from
/var/target/ to /etc/target/. However, if the directory passed to
"dbroot" does not exist, the kernel returns an "invalid argument"
error:
[Errno 22] Invalid argument
With this patch, a more meaningful message is displayed instead:
Cannot set dbroot to /etc/target. Please check if this directory exists.
This patch fixes issue #103.
=> Display a more meaningful error when targetcli cannot change "dbroot"

rtslib/fabric.py
Many distros(such as CentOS 6) still use python 2.6. but in fabric.py, uses new set
initialization syntax introduced by python 2.7
We can consider for legacy distros using python 2.6 as we using legacy but not
deprecated syntax
Signed-off-by: Ji-Hyeon Gim <potatogim@potatogim.net>
=> More compatibility syntax for legacy distros

rtslib/root.py
rtslib never creates hba directories without a storage object within it,
but if under some circumstance these existed then clear_existing() wouldn't
remove them, since StorageObject::all()'s glob ignores them.
Add code to ensure these are also removed.
Signed-off-by: Andy Grover <agrover@redhat.com>
=> Remove hba-only directories in clear_existing()

rtslib/fabric.py
The name used in released products is xen-pvscsi, not xen_pvscsi.
Fixes: 2bcc4cd ("Add support for xen-scsiback")
Signed-off-by: Olaf Hering <olaf@aepfle.de>
=> Correct name for Xen pvscsi

rtslib/utils.py
Fixes crash when using a block device with the fileio backstore.
Fixes #116
=> Fix unqualified reference to pyudev.Device

rtslib/node.py
curretly if there exist any stale hba-only directories,
$ ls /sys/kernel/config/target/core/user_0/
hba_info  hba_mode
Then backend creation fails,
$ targetcli /backstores/fileio create block file 1M
This _Backstore already exists in configFS
We will have to restart target.service or restore the configuration
again to clear the stale hba-only dirs.
This patch checks for hba directory before creating one,
if it is already existing and found to be stale then removes it.
Thanks to "Maurizio Lombardi <mlombard@redhat.com>" for debugging along
=> create: remove stale hba-only dir

rtslib/target.py
Currently there's an unnecessary limitation of 256 LUNs per target, which is
not enforced in the kernel driver. We keep a limit of 256 Mapped LUNs per
initiator as required by the iSCSI protocol.
The end goal of this change is to be able to server many initiators using a single target.
The value of 65535 was chosen arbitrarily as I'm not aware of the exact limit.
Note that [targetcli](https://github.com/open-iscsi/targetcli-fb) also needs to be modified (slightly) to account for this change.
=> Allow creating more than 256 LUNs per target

rtslib/tcm.py
Add format control constructor arg so user does not have to hack
in extra settings through the config option.
Related to PR:
https://github.com/open-iscsi/rtslib-fb/pull/122#issuecomment-371242638
=> tcmu: add control constructor arg

rtslib/alua.py
Problem:
---
$ cat myconfig.json
```
{
"storage_objects": [
{
"alua_tpgs": [
{
"alua_access_type": 0,
"name": "glfs_tg_pt_gp",
"tg_pt_gp_id": 1
}
],
"config": "glfs/test@192.168.124.227/block-store/2e189467-00ae-4388-bbd2-a8b4df154671",
"name": "blockX",
"plugin": "user",
"size": 1073741824
}
],
"targets": []
}
```
$ targetcli restoreconfig myconfig.json
All configuration cleared
'alua_access_state'
And attributes won't be effected as per myconfig.json:
$ targetcli/backstores/user:glfs/blockX/alua/glfs_tg_pt_gp get alua alua_access_type
alua_access_type=3
Fix:
---
This patch fix the problem by calling setattr for available attribs in the
configfile and rest all will be as per kernel defaults.
=> restoreconfig: fix alua tpg config setup

rtslib/tcm.py
Problem:
-----------
```
$ targetcli /backstores/user:glfs create blockX1 1073741824 \
test@192.168.124.227/block-store/e59309bb-d591-4121-a891-e98ff3416446,max_data_area_mb=32
$ targetcli / saveconfig
$ cat /etc/target/saveconfig.json
{
"storage_objects": [
{
"alua_tpgs": [],
"attributes": {
...
},
"config": "glfs/test@192.168.124.227/block-store/e59309bb-d591-4121-a891-e98ff3416446",
"hw_max_sectors": 128,
"name": "blockX1",
"plugin": "user",
"size": 1073741824,
"wwn": "3aa072d6-a007-45a3-8eac-e85b53655515"
}
],
"targets": []
}
```
Note max_data_area_mb is not dumped into the configfile and hence on restart of
target service or node reboot this storageObject property is lost.
Fix:
----
This patch make sure to dump control string containing control=value tuples, like:
```
$ cat …
```
=> saveconfig: dump control string containing control=value tuples

rtslib/root.py
$ ls /etc/target/
backup
$ targetcli /backstores/user:glfs/testX saveconfig
[Errno 2] No such file or directory: '/etc/target/saveconfig.json'
=> saveconfig: fix failure in absence of save file

rtslib/root.py, rtslib/tcm.py
currently, we can use block-level save feature for create command and
reconfig of different attributes, but there is no way to use block-level
feature for delete command.
This patch introduces 'save' flag (False on default), which can trigger
saveconfig internally as part of delete command.
$ targetcli /backstores/user:glfs delete test save=True
Deleted storage object test.
=> [rtslib] saveconfig: way for block-level save with delete command

rtslib/root.py
build.log:
---------
[...]
*** Error compiling '/builddir/build/BUILDROOT/python-rtslib-2.1.fb68-1.el8.noarch/usr/lib/python3.6/site-packages/rtslib/root.py'...
File "/usr/lib/python3.6/root.py", line 191
except IOError, e:
^
SyntaxError: invalid syntax
*** Error compiling '/builddir/build/BUILDROOT/python-rtslib-2.1.fb68-1.el8.noarch/usr/lib/python3.6/site-packages/rtslib_fb/root.py'...
File "/usr/lib/python3.6/root.py", line 191
except IOError, e:
[...]
Thanks to Maurizio Lombardi <mlombard@redhat.com> for finding it.
=> fix compiler warning

rtslib/utils.py
If you use a partition instead of the whole device as the backstore device,
rtslib will always report its size as 0 bytes.
This happens because rtslib tries to read the "queue/logical_block_size"
attribute, which can only be found in the parent's node.
This patch fixes the bug by loading the parent node's attributes if
it detects that the device is a partition.
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>
=> report the correct size for partitions

rtslib/node.py, rtslib/target.py
A recent kernel change (see commit 6baca7601bdee2e5) makes
the pi_prot_format protection information attribute write-only,
since it always returned 0 when being read. This commit is being
reverted, but it still brought up the prospect of write-only
attributes.
Currently, when doing a dump(), rtslib iterates through all
readable attributes to decide which ones to save as part of
our current state, but saving write-only attributes
makes no sense, since we cannot read them to capture their
value. Towards this end, enhande the _list_files() internal
method to allow filtering on whether the file is writable
as well as whether or not it is readable. Then modify
list_attributes() to allow this new parameter and modify
dump() to request only R/W attributes.
=> Handle write-only attributes.

rtslib/root.py
Currently the location of the targetcli configuration file is not
configurable (saveconfig.json). The location is : /etc/target
Some users use stateless VMs, with just a persistent device
mounted under /var/lib/diskless.
In order to circumvent the non configurable location of
saveconfig.json, they create a symbolic link in /etc/target
pointing to /var/lib/diskless
Unfortunately, the rtslib save_to_file() function breaks
this symbolic link and creates a new regular file in place of it,
due to the creation of a saveconfig.json.temp file which is
then renamed to saveconfig.json using the os.rename() function.
This patch replace os.rename() with shutil.copyfile() + os.remove(),
using copyfile() instead of rename() will preserve the symbolic link
Signed-off-by: Maurizio Lombardi …
=> save_to_file() function breaks symbolic link when saving configuration

rtslib/tcm.py
$ targetcli /backstores/user:glfs create name=block size=1048576 \
cfgstring=hosting-volume@192.168.195.164/block-store/d85244f7-88e9-4b28-922d-373fa9f59f24 \
control=max_data_area_mb=64,hw_block_size=1024 wwn=d85244f7-88e9-4b28-922d-373fa9f59f24
$ targetcli / saveconfig
$ cat /etc/target/saveconfig.json
{
"storage_objects": [
{
"alua_tpgs": [],
"attributes": {
...
},
"config": "glfs/hosting-volume@192.168.195.164/block-store/d85244f7-88e9-4b28-922d-373fa9f59f24",
"control": "max_data_area_mb=64,hw_block_size=1024",
"hw_max_sectors": 128,
"name": "block",
"plugin": "user",
"size": 1048576,
"wwn": "d85244f7-88e9-4b28-922d-373fa9f59f24"
}
],
"targets": []
}
Signed-off-by: Xiubo Li <xiubli@redhat.com>
=> saveconfig: add hw_block_size support in control string

rtslib/__init__.py, setup.py
Before:
$ python -c "import rtslib_fb; print(rtslib_fb.\_\_version_\_)"
GIT_VERSION
After:
$ python -c "import rtslib_fb; print(rtslib_fb.\_\_version_\_)"
2.1.69
Also rectified few other public exported variables
=> rtslib: fix __version__

rtslib/root.py
Problem:
-------
Currently if the 'targetcli ls' is not empty, then restoreconfig command will
bail-out before even checking if the supplied config file has conflicting names
of storage objects and target objects
Solution:
--------
If the supplied configuration file doesn't have conflicting storage objects
and target objects then load it.
=> restoreconfig: support restore when list is non-empty

rtslib/root.py
Problem:
-----------
'targetcli restoreconfig [savefile] [target=...]' works for first target only
in the saveconfig.json and fails/skips for others silently.
Solution:
-----------
Just an indentation fix, yet very severe.
=> restoreconfig: fix skipping of targets [re]loading

rtslib/root.py
Fixes: #161
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>
=> saveconfig: open the temp configfile with modes set

rtslib/root.py
This issues a warning on python 3.8+.
=> Fix "is not" with a literal SyntaxWarning

rtslib/root.py
since we used O_WRONLY with os.open(), lets stick to
same mode with os.fdopen() too
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>
=> save_to_file: fix fd open mode

rtslib/utils.py
Resolves https://github.com/open-iscsi/targetcli-fb/issues/158
=> Fix EPERM errors with scsi_generic devices

rtslib/root.py
Previously we had to replace shutil.copyfile() with shutil.copy(), because we want to copy the file permissions to the destination file along with the data.                                                      
It appears that shutil.copy() is opening the destination file with wide access (0666) first, and then it starts copying the data and at the end it is copying the permissions from source file to destination. 
If we closely notice there appears a window between destination file is opened vs permissions are set on the destination file, which could allow a user to get the contents of the file when opening it at the right time.                                                               
The behavior is a bit unsteady here, it is noticed that, when saveconfig.json file exists, then on …
=> rtslib: safely call shutil.copy() 

rtslib/utils.py
Using O_RDWR flag for read-only devices will always result in
is_dev_in_use() to return False while sg devices require O_RDWR flag.
Hence, determine this difference programmatically and use the flags
appropriately.
Resolves https://github.com/open-iscsi/rtslib-fb/issues/170
Fixes: 964520037320 ("Fix EPERM errors with scsi_generic devices")
Signed-off-by: Sudhakar Panneerselvam <sudhakar.panneerselvam@oracle.com>
=> rtslib: Use O_RDWR for sg devices alone.

rtslib/target.py
Currently rtslib forbids TPG Tag 0. According to
https://tools.ietf.org/html/rfc7143#section-13.9 this is perfectly legal
value, and I've tested it with Linux, Windows, ESXi and AIX initiators.
This commit relaxes the restriction and allows TPG Tag to be 0. I've
kept current behavior in automatic tags assignment so nothing changes
there (e.g. the first TPG will be 1 unless the user explicitly tells
otherwise).
=> Relax restrictions on TPG Tag range

rtslib/tcm.py
Starting from kernel 5.13 tcmu (user based backend) supports
config parameter DataPagesPerBlk alias data_pages_per_blk.
This change enables rtslib to save the new config parameter
to saveconfig.json.
Signed-off-by: Bodo Stroesser <bostroesser@gmail.com>
#####
Short explanation of the new tcmu config param:
The parameter allows to specify what granularity is used in
data area provided via uio device. Data space now appears to
userspace as chunks of data_pages_per_blk * PAGE_SIZE.
If the default value 1 of data_pages_per_blk is not changed,
tcmu behaves like unchanged.
Setting data_pages_per_blk > 1 allows tcmu to allocate less
but bigger chunks, which makes allocation quicker. Also
userspace will see less iovecs per data transfer. If chunk
size is as big as biggest possible data transfer, …
=> tcmu: add support for config param data_pages_per_blk

rtslib/root.py
Thanks to a new kernel patch [1], the LIO driver now lets the user change
the dbroot directory even if some target modules are already registered
(if some conditions are met).
rtslib should let the user set their preferred root directory without
arbitrary checks and let the kernel decide if this is allowed or not.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git/commit/?h=for-next&id=80890c5ea068661d6fe4a34beb362ca0f2c49c90
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>
=> dbroot: let the user change the dbroot directory freely.

rtslib/tcm.py
Importing the module alone shouldn't require root privileges. This fixes simple import tests in downstream projects.
=> rtslib: Don't create /var/run on import

rtslib/utils.py
This fix prevents errors when creating ACLs for some FC cards, and NPIV devices. I first noticed this when I was trying to create and ACL for a system Z server. This fix has been tested on my server, and produces no issues. It fixes issue #139.
=> Fix inability to create ACLs for some FC cards

setup.py
Will match __version__ with trailing .g<hash> but will not include .g<hash> in installed module version.
Fixes #188.
Signed-off-by: Brendan Cunningham <bcunningham@cornelisnetworks.com>
=> setup.py: match __version__ with optional trailing ".g<hash>".

rtslib/target.py
The kernel is able to handle more than 255 LUNs since version 4.2
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>
=> rtslib: remove the limit of 255 max mapped LUNs

rtslib/utils.py
There's a bug ( #196 ) that causes trying to create tape passthrough entries to fail on os.close(). As this should always succeed or fail gracefully, silently ignoring the failed close() here should be safe.
=> Silently ignore OSError on os.close()

.gitignore, .pre-commit-config.yaml, rtslib/utils.py, rtslib_fb.py
I think it would be nice to get rid of the`__all__`, but from what I can see in targetcli_fb it's not really possible without changing it simultaneously.
=> Add rtslib_fb import compability

pyproject.toml
After changing the package name from `rtslib` to `rtslib-fb` to be able to publish on PyPI, the build system no longer correctly autodetects the rtslib package, as it matches the rtslib_fb.py file only. This change will set the rtslib and rtslib_fb.py explicitly in the same way as in configshell-fb, which is using the same compatibility/legacy layers.  
Tested on Fedora 41, both rtslib and rtslib_fb imports are working as expected and source tarball seems to contain everything.
=> Explicitly set build target wheel packages

rtslib/root.py, scripts/convert-to-json
There are places where the code does this pattern:
with Path(some_path).open as f:
... (do stuff)
But that generates an error message like:
/> restoreconfig temp.json
Traceback (most recent call last):
File "/usr/bin/targetcli", line 8, in <module>
sys.exit(main())
~~~~^^
File "/usr/lib/python3.13/site-packages/targetcli/targetcli_shell.py", line 313, in main
shell.run_interactive()
~~~~~~~~~~~~~~~~~~~~~^^
File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 899, in run_interactive
self._cli_loop()
~~~~~~~~~~~~~~^^
File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 728, in _cli_loop
self.run_cmdline(cmdline)
~~~~~~~~~~~~~~~~^^^^^^^^^
File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 842, in run_cmdline
self._execute_command(path, command, …
=> Fix issue with Path(...).open: needs parenthesis

rtslib/targetctl.py
The targetctl.py script was using /usr/bin/python, even though this package has been ported to python3.
This makes installing it on modern systems fail. Change it to /usr/bin/python3.
=> Remove use of /usr/bin/python

rtslib/fabric.py
When converted to path link, Infiniband gid search path was replaced with a double wildcard '**' causing no WWNs to be found and SRPT to be unusable: No such path /srpt
This due to HCA in /sys/class/infiniband being symlinks: $ ll /sys/class/infiniband
total 0
lrwxrwxrwx 1 root root 0 Jun 23 11:31 mlx5_0 -> ../../devices/pci0000:00/0000:00:02.6/0000:07:00.0/infiniband/mlx5_0
recurse_symlinks=True cannot be used here as HCA directories contains a 'subsystem' symlink
pointing back to /sys/class/infiniband
Replace the double wildcard with a single one to revert to the previous behaviour and be consistent with other fabrics.
Fixes: d3abd5df9e06 ("Convert codebase to pathlib")
Reviewed-by: Lee Duncan <lduncan@suse.com>
=> fabric: fix search path for SRPT wwn
