open-iscsi/rtslib-fb

- rtslib/fabric.py
- rtslib/root.py
- rtslib/target.py
Here are three patches for rtslib-fb to fix several errors and warnings reported by [Pylint](http://www.pylint.org/).
> Pylint fixes

- rtslib/utils.py
Signed-off-by: mulhern <amulhern@redhat.com>
> Make use of pyudev package as much as possible in utils module.

- rtslib/utils.py
Return None if device path is a partition in convert_scsi_path_to_hctl.
In convert_scsi_hctl_to_path ensure that device is not a partition in the
most correct and efficient way. Get exactly the set of devices that are
descendants of the scsi device and are block devices and have type disk.
This should be a singleton, or the empty set.
Signed-off-by: mulhern <amulhern@redhat.com>
> Make sure to properly avoid treating partitions the same as disk.

- rtslib/utils.py
There is a race condition in mount_configfs, this is a possible workaround for the issue.
> Fix mount race condition

- example-debian/control
- example-debian/rules
I found these tweaks necessary to build Debian 8 (jessie) packages with sbuild.  But then I no expert.
> fixes to debian package scripts

- README.md
- doc/saveconfig.json.5
- doc/targetctl.8
- setup.py
> Change the URL of the GitHub repo to the open-iscsi organization

- README.md
> Add Gentoo to the list of distributions that ship rtslib-fb

- rtslib/__init__.py
- rtslib/alua.py
- rtslib/root.py
- rtslib/target.py
- rtslib/tcm.py
This patchset adds basic ALUA group creation/deletion and LUN attachment support to rtslib-fb.
> ALUA support for rtslib-fb

- rtslib/tcm.py
Support hw_max_sectors setting for tcmu added in this patch:
commit 3abaa2bfdb1e6bb33d38a2e82cf3bb82ec0197bf
Author: Mike Christie <mchristi@redhat.com>
Date:   Wed Mar 1 23:14:39 2017 -0600
tcmu: allow hw_max_sectors greater than 128
Signed-off-by: Mike Christie <mchristi@redhat.com>
> Support tcmu hw max sectors

- setup.py
> Add missing dependency on six in setup.py

- systemd/README.md
- systemd/target.service
resolves #119
Signed-off-by: Andy Grover <agrover@redhat.com>
> Ship a systemd service file

- rtslib/root.py
Add an option to update configuration for single block at a time.
As of today changes done for one single block needs the whole configuration
update.
This patch introduces a new option 'block_name' to saveconfig command
$ targetcli help
[...]
AVAILABLE COMMANDS
[...]
- saveconfig [savefile] [block_name]
- sessions [action] [sid]
- set [group] [parameter=value...]
- status
- version
Batch mode:
----------
$ targetcli / saveconfig block_name=block1
Interactive mode:
----------------
$ targetcli
targetcli shell version 2.1.fb48
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.
/> / saveconfig block_name=block1
Last 26 configs saved in /etc/target/backup.
Configuration saved to /etc/target/saveconfig.json
Signed-off-by: Prasanna Kumar Kalever …
> saveconfig: support saving configuration at block granularity

- rtslib/tcm.py
This feature was recently added into the Linux Kernel:
76931420c876 ("scsi: target: target/file: Add support of direct and async I/O")
> tcm: allow to enable asynchronous I/O for file backing stores

- rtslib/tcm.py
The ceph tools might have multiple daemons making and querying the system.
To avoid invalidating the cache for every creation and lookup this allows
tools like ours to avoid the cache.
If the caller passed in the index during creations or lookups then use
that value instead of building/quering the cache.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> Allow bs_cache to be bypassed

- rtslib/root.py
Signed-off-by: tang.wenji <tang.wenji@zte.com.cn>
> remove extra semicolons in _get_saveconf

- rtslib/fabric.py
- rtslib/root.py
Resolves [bug 1676669](https://bugzilla.redhat.com/show_bug.cgi?id=1676669) on Red Hat Bugzilla.
> Do not change dbroot after drivers have been registered

- rtslib/fabric.py
The PR adds support of the Emulex HBAs in target mode (works on Linux v5.14+) and changes the way how fabric modules filters supported wwns.
> efct support

- rtslib/tcm.py
Creating multiple backstores at the same time without specifying the
index parameter may cause this exception.
The reason is that _Backstore is allocated the same new index value.
Signed-off-by: Zou Mingzhe mingzhe.zou@easystack.cn
> fix "This _Backstore already exists in configFS" exception

- rtslib/fabric.py
target has been added cpus_allowed_list attribute in sysfs.
Therefore, the rtslib should handle the new attribute:
1. add cpus_allowed_list item in target_names_excludes
2. add cpus_allowed_list feature in ISCSIFabricModule
Signed-off-by: Zou Mingzhe mingzhe.zou@easystack.cn
> handle target kernel module new attribute cpus_allowed_list

- rtslib/target.py
alua_tg_pt_offline
alua_tg_pt_status
alua_tg_pt_write_md
> rtslib/LUN: add some ALUA property

- .github/workflows/pre-commit.yml
- .github/workflows/publish.yml
Copied from https://github.com/open-iscsi/configshell-fb/pull/79
> Add PyPA publish and pre-commit check workflows

- pyproject.toml
package name change (to be able to publish on pypi)
> Fix the program name in pyproject.toml

- rtslib/tcm.py
This allows users to control if we open a iblock device with exclusive rights or not.
This kernel patch is needed:
https://lore.kernel.org/linux-scsi/20250721185145.20913-1-michael.christie@oracle.com/T/#u
It's currently in the SCSI maintainer's tree so should be upstream soon, so I wanted to get the userspace review going.
> BlockStorageObject: Add support for exclusive ownership
